fda_daily_values = {
    "nutrients": [
        {"name": "Added sugars", "daily_value": "50g"},
        {"name": "Biotin", "daily_value": "30mcg"},
        {"name": "Calcium", "daily_value": "1300mg"},
        {"name": "Chloride", "daily_value": "2300mg"},
        {"name": "Choline", "daily_value": "550mg"},
        {"name": "Cholesterol", "daily_value": "300mg"},
        {"name": "Chromium", "daily_value": "35mcg"},
        {"name": "Copper", "daily_value": "0.9mg"},
        {"name": "Dietary Fiber", "daily_value": "28g"},
        {"name": "Fat", "daily_value": "78g"},
        {"name": "Folate/Folic Acid", "daily_value": "400mcg DFE"},
        {"name": "Iodine", "daily_value": "150mcg"},
        {"name": "Iron", "daily_value": "18mg"},
        {"name": "Magnesium", "daily_value": "420mg"},
        {"name": "Manganese", "daily_value": "2.3mg"},
        {"name": "Molybdenum", "daily_value": "45mcg"},
        {"name": "Niacin", "daily_value": "16mg NE"},
        {"name": "Pantothenic Acid", "daily_value": "5mg"},
        {"name": "Phosphorus", "daily_value": "1250mg"},
        {"name": "Potassium", "daily_value": "4700mg"},
        {"name": "Protein", "daily_value": "50g"},
        {"name": "Riboflavin", "daily_value": "1.3mg"},
        {"name": "Saturated fat", "daily_value": "20g"},
        {"name": "Selenium", "daily_value": "55mcg"},
        {"name": "Sodium", "daily_value": "2300mg"},
        {"name": "Thiamin", "daily_value": "1.2mg"},
        {"name": "Total carbohydrate", "daily_value": "275g"},
        {"name": "Vitamin A", "daily_value": "900mcg RAE"},
        {"name": "Vitamin B6", "daily_value": "1.7mg"},
        {"name": "Vitamin B12", "daily_value": "2.4mcg"},
        {"name": "Vitamin C", "daily_value": "90mg"},
        {"name": "Vitamin D", "daily_value": "20mcg"},
        {"name": "Vitamin E", "daily_value": "15mg"},
        {"name": "Vitamin K", "daily_value": "120mcg"},
        {"name": "Zinc", "daily_value": "11mg"},
    ],
    "units_of_measure": {
        "g": "grams",
        "mg": "milligrams",
        "mcg": "micrograms",
        "mg NE": "milligrams of niacin equivalents",
        "mcg DFE": "micrograms of dietary folate equivalents",
        "mcg RAE": "micrograms of retinol activity equivalents",
        "IU": "international units",
    },
}
